# fly.toml app configuration file generated for bkk on 2024-02-03T11:45:48-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bkk'
primary_region = 'sea'
console_command = '/code/manage.py shell'

[build]

[env]
  PORT = '8000'
  DEBUG = 'False'
  ENVFILE = '0'
  #
  ADD_FLY_HOST = 'true'

[http_service]
  internal_port = 8000
  force_https = true
  # auto_stop_machines = true
  # auto_start_machines = true
  # min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
