# fly.toml app configuration file generated for bkk on 2024-02-03T11:45:48-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bkk'
primary_region = 'sea'
console_command = '/code/manage.py shell'

[build]

[env]
  PORT = '8000'
  DEBUG = 'False'
  ENV_FILE = '0'
  DB_ENGINE="django.db.backends.sqlite3"
  DB_NAME = "/data/db.sqlite3"
  # TODO: use this env to set CMD
  # GUNICORN_LOG_FILE = "/data/gunicorn.log"
  APP_LOG_FILE = "/data/app.log"
  #
  ADD_FLY_HOST = 'true'

[http_service]
  internal_port = 8000
  force_https = true
  # auto_stop_machines = true
  # auto_start_machines = true
  # min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

[mounts]
  source = "app_data"
  destination = "/data"

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
